#!/bin/bash

# https://fontawesome.com/cheatsheet

usage() {
  echo " "	
  echo "Usage:  dwm-bar-functions -[ OPTIONS ]"
  echo " "	
  echo "Options: "	
  echo "   -b : battery"
  echo "   -v : VPN"
  echo "   -m : RAM"
  echo "   -d : disk usage"
  echo "   -l : cpu load"
  echo "   -a : volume"
  echo "   -t : data-time"
  echo "   -c : cmus info"
  echo "   -h : help"
  echo " "	
  exit 2
}


getBattery () {
    # /sys/class/power_supply/BAT0/capacity
    # /sys/class/power_supply/BAT0/status

	mycommand=$(acpi)
	mycommand=$( echo $mycommand | sed 's/ remaining//' | sed 's/ until charged//' | sed 's/%//' )
	# echo $mycommand

	perc=$( echo "$mycommand" | awk '{print $4}' | sed 's/,//' )
	#echo $perc

	if [[ $mycommand == *"Charging"* ]]
	then
		suppltext=" "
	elif [[ $mycommand == *"Discharging"* ]]
	then
		timevar=$( echo $mycommand | awk '{print $NF}')
		timevar=${timevar%:*}
		suppltext=" ($timevar)"
	fi

	# print the value to the battery block
	#echo "$perc%$suppltext"
	if [[ $mycommand == *"Full"* ]]
	then
		echo " Full"
	else
		echo "$perc%$suppltext"
	fi



	# adding colors (if needed)
	#if [ $perc -lt 20 ]
	#then
	#	echo " ";
	#	echo "$colorPANIC";
	#elif [ $perc -lt 50 ]
	#then
	#	echo " ";
	#	echo "$colorALERT";
	#fi
}

getVpnActive() {
    command=$(ip link show | grep tunsnx | wc -l)
    if [[ "$command" == "1" ]]
    then
        #echo "[VPN]"
        echo " [$(tail -n 1 /tmp/vpn_log)]"
    else
        echo " "
    fi
}

getMem () {
	usedmem=$(free -m | grep Mem | awk '{print $3}')
	totalmem=$(free -m | grep Mem | awk '{print $2}')
	freemem=$(($totalmem-$usedmem))
	usedpercent=$((100-($freemem*100)/$totalmem))

	echo " $usedpercent%"
}


getDiskUsage () {
	#  /dev/sda2   -->>  /
	#  /dev/sda3   -->>  /opt
	#  /dev/sda4   -->>  /home
	
	diskfree=$(df -h -P -l $1 | grep sda4 | awk '{print $4}')
	freeperc=$(df -h -P -l $1 | grep sda4 | awk '{print $5}')
	freeArranged="${freeperc%?}"
	echo " $diskfree"
}

getCpuLoad () {
	load=$( mpstat 1 1 | grep Average | awk '{ print 100 - $12 }' | awk '{print int($0)}' )
	echo " $load%"
}

getVolume() {
	echo " $( ~/bin/audioscript getvalue )"
}

getDate() {
	echo " $(date '+%a %d/%m/%Y %H:%M')"
}

getCmusInfo() {
	if ps -C cmus > /dev/null; then
	   artist=`cmus-remote -Q | 
	      grep --text '^tag artist' | 
	      sed '/^tag artistsort/d' | 
	      awk '{gsub("tag artist ", "");print}'`
	   title=`cmus-remote -Q  | 
	      grep --text '^tag title' | 
	      sed -e 's/tag title //' |
	      awk '{gsub("tag title ", "");print}'`
	   echo " [$artist - $title]  "; 
	else 
		echo ""; 
	fi
}


# si no hi ha paràmtre o no comença per "-", error !
[ -z $1 ] && usage
[[ $1 != -* ]] && usage

while getopts ':bvmdlatch' c
do
  case $c in
    b) getBattery ;; 
    v) getVpnActive ;;
    m) getMem ;;
    d) getDiskUsage ;;
    l) getCpuLoad ;;
    a) getVolume ;;
    t) getDate ;;
    c) getCmusInfo ;;
    h) usage ;;
    :) usage ;;
    ?) usage ;;
  esac
done
