#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1 &
wmname LG3D &
compton -f &
dunst &
#urxvtd -q -o -f &
#manage-monitors &
#xautolock -time 20 -locker "$HOME/bin/i3/lock" &
wallpaper-loop &
xrdb ~/.Xresources &

#dwm-bar &
dwmblocks &
#sxhkd -c ~/.config/sxhkd/sxhkdrc.dwm &

exec dwm
