#!/bin/bash

color0=$(xrdb -query | grep  color0   | awk '{print $2}')
color1=$(xrdb -query | grep  'color1:'| awk '{print $2}')
color2=$(xrdb -query | grep  color2   | awk '{print $2}')
color3=$(xrdb -query | grep  color3   | awk '{print $2}')
color4=$(xrdb -query | grep  color4   | awk '{print $2}')
color5=$(xrdb -query | grep  color5   | awk '{print $2}')
color6=$(xrdb -query | grep  color6   | awk '{print $2}')
color7=$(xrdb -query | grep  color7   | awk '{print $2}')
color8=$(xrdb -query | grep  color8   | awk '{print $2}')
color9=$(xrdb -query | grep  color9   | awk '{print $2}')
color10=$(xrdb -query | grep color10  | awk '{print $2}')
color11=$(xrdb -query | grep color11  | awk '{print $2}')
color12=$(xrdb -query | grep color12  | awk '{print $2}')
color13=$(xrdb -query | grep color13  | awk '{print $2}')
color14=$(xrdb -query | grep color14  | awk '{print $2}')
color15=$(xrdb -query | grep color15  | awk '{print $2}')
background=$(xrdb -query | grep background | awk '{print $2}')
foreground=$(xrdb -query | grep foreground | awk '{print $2}')
cursorColor=$(xrdb -query | grep cursorColor | awk '{print $2}')
cursorColor2=$(xrdb -query | grep cursorColor2 | awk '{print $2}')
backgroundalt="#312e30"
foregroundalt="#949d9f"

# https://fontawesome.com/cheatsheet

getBattery () {
    # /sys/class/power_supply/BAT0/capacity
    # /sys/class/power_supply/BAT0/status

	mycommand=$(acpi)
	mycommand=$( echo $mycommand | sed 's/ remaining//' | sed 's/ until charged//' | sed 's/%//' )
	# echo $mycommand

	perc=$( echo "$mycommand" | awk '{print $4}' | sed 's/,//' )
	#echo $perc

	if [[ $mycommand == *"Charging"* ]]
	then
		suppltext=" "
	elif [[ $mycommand == *"Discharging"* ]]
	then
		timevar=$( echo $mycommand | awk '{print $NF}')
		timevar=${timevar%:*}
		suppltext=" ($timevar)"
	fi

	# print the value to the battery block
	#echo "$perc%$suppltext"
	if [[ $mycommand == *"Full"* ]]
	then
		echo " Full"
	else
		echo "$perc%$suppltext"
	fi



	# adding colors (if needed)
	#if [ $perc -lt 20 ]
	#then
	#	echo " ";
	#	echo "$colorPANIC";
	#elif [ $perc -lt 50 ]
	#then
	#	echo " ";
	#	echo "$colorALERT";
	#fi
}

getVpnActive() {
    command=$(ip link show | grep tunsnx | wc -l)
    if [[ "$command" == "1" ]]
    then
        #echo "[VPN]"
        echo "[$(tail -n 1 /tmp/svn_log)]"
    else
        echo ""
    fi
}

getMem () {
	usedmem=$(free -m | grep Mem | awk '{print $3}')
	totalmem=$(free -m | grep Mem | awk '{print $2}')
	freemem=$(($totalmem-$usedmem))
	usedpercent=$((100-($freemem*100)/$totalmem))

	echo " $usedpercent%"
}


getDiskUsage () {
	#  /dev/sda2   -->>  /
	#  /dev/sda3   -->>  /opt
	#  /dev/sda4   -->>  /home
	
	diskfree=$(df -h -P -l $1 | grep sda4 | awk '{print $4}')
	freeperc=$(df -h -P -l $1 | grep sda4 | awk '{print $5}')
	freeArranged="${freeperc%?}"
	echo " $diskfree"
}

getCpuLoad () {
	load=$( mpstat 1 1 | grep Average | awk '{ print 100 - $12 }' | awk '{print int($0)}' )
	echo " $load%"
}

getVolume() {
	echo " $( ~/bin/audioscript getvalue )"
}

getDate() {
	echo " $(date '+%a %d/%m/%Y %H:%M')"
}

getCmusInfo() {
	if ps -C cmus > /dev/null; then
	   artist=`cmus-remote -Q | 
	      grep --text '^tag artist' | 
	      sed '/^tag artistsort/d' | 
	      awk '{gsub("tag artist ", "");print}'`
	   title=`cmus-remote -Q  | 
	      grep --text '^tag title' | 
	      sed -e 's/tag title //' |
	      awk '{gsub("tag title ", "");print}'`
	   echo " [$artist - $title]  "; 
	else 
		echo ""; 
	fi
}


while true; do
    xsetroot -name "$(getVpnActive)$(getCmusInfo)  $(getVolume)   $(getBattery)   $(getDiskUsage)   $(getMem)   $(getDate)" 
   #xsetroot -name "$(getCmusInfo)  $(getVolume)   $(getBattery)   $(getCpuLoad)   $(getDiskUsage)   $(getMem)   $(getDate)" 
   #xsetroot -name "$(getCmusInfo) | $(getCpuLoad) | $(getDiskUsage) | $(getMem) | $(date '+%a %d/%m/%Y %H:%M')" 
   sleep 3s
done &

