#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &

colorActive=$( $HOME/bin/getcolor purple )
colorFocused=$( $HOME/bin/getcolor cyan )
background=$( $HOME/bin/getcolor bg )

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          5    
bspc config bottom_padding       0    
bspc config right_padding        0    
bspc config left_padding         0    

bspc config split_ratio              0.50
bspc config borderless_monocle       true
bspc config gapless_monocle          true
bspc config single_monocle           true
bspc config pointer_follows_monitor  true

bspc config normal_border_color "$background"
bspc config active_border_color "$colorActive"
bspc config focused_border_color "$colorFocused"
bspc config presel_feedback_color "#2a2829"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# scratchpads (using instance name, not class name)
bspc rule -a "*:scratchpad"     sticky=on state=floating
bspc rule -a "*:scratchurxvt"   sticky=on state=floating
bspc rule -a "*:stmusic"        sticky=on state=floating

# ------------------------
#   starting processes
# ------------------------ 
xsetroot -cursor_name left_ptr &
# urxvtd -q -o -f &
# compton  &
# xbacklight -set 50 &
# light -S 50.0 &
wmname LG3D &
$HOME/bin/audioscript default &
# mkdir -p /tmp/sdr &
# xautolock -time 15 -locker "$HOME/bin/lock" &
$HOME/bin/wallpaper-loop &
# xrdb $HOME/.config/Xresources/Xresources &

# ------------------
#   launching bar  
# ------------------
$HOME/bin/bspwm/launch-bar.sh &
#$HOME/bin/bspwm/launch-bar.sh polybar
