#! /bin/bash

# carreguem l'estructura de colors
. panel_colors


num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		D*)
			# data output
			data="%{F$COLOR_DATA_FG} ${line#?} %{F-}"
			;;
		V*)
			# volume
			volume="%{F$COLOR_VOLUME_FG} ${line#?} %{F-}"
			;;
		H*)
			# hora
			hora="%{F$COLOR_HORA_FG} ${line#?} %{F-}"
			;;
		A*)
			# VPN
			vpn="%{F$COLOR_VPN_FG} ${line#?} %{F-}"
			;;
		M*)
			# music
			music="%{F$COLOR_MUSIC_FG} ${line#?} %{F-}"
			;;
		R*)
			# memory
			mem="%{F$COLOR_MEM_FG} ${line#?} %{F-}"
			;;
		W*)
			# bspwm's state
			wm=
			wm1=
			wm2=
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								on_focused_monitor=
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								on_focused_monitor=1
								;;
						esac
						[ $num_mon -lt 2 ] && shift && continue
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						monitor_name=${name}
						[ -z "$first_monitor_name" ] && first_monitor_name=$name
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								UL=$BG
								;;
							F*)
								if [ "$on_focused_monitor" ] ; then
									# focused free desktop
									FG=$COLOR_FOCUSED_FREE_FG
									BG=$COLOR_FOCUSED_FREE_BG
									UL=$BG
								else
									# active free desktop
									FG=$COLOR_FREE_FG
									BG=$COLOR_FREE_BG
									UL=$COLOR_FOCUSED_FREE_BG
								fi
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								UL=$BG
								;;
							O*)
								if [ "$on_focused_monitor" ] ; then
									# focused occupied desktop
									FG=$COLOR_FOCUSED_OCCUPIED_FG
									BG=$COLOR_FOCUSED_OCCUPIED_BG
									UL=$BG
								else
									# active occupied desktop
									FG=$COLOR_OCCUPIED_FG
									BG=$COLOR_OCCUPIED_BG
									UL=$COLOR_FOCUSED_OCCUPIED_BG
								fi
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								UL=$BG
								;;
							U*)
								if [ "$on_focused_monitor" ] ; then
									# focused urgent desktop
									FG=$COLOR_FOCUSED_URGENT_FG
									BG=$COLOR_FOCUSED_URGENT_BG
									UL=$BG
								else
									# active urgent desktop
									FG=$COLOR_URGENT_FG
									BG=$COLOR_URGENT_BG
									UL=$COLOR_FOCUSED_URGENT_BG
								fi
								;;
						esac
						# with unerlines:
						#wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{+u}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}%{-u}"
						# without unerlines:
						wm="${wm}%{F${FG}}%{B${BG}}%{U${UL}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						#if [ "$on_focused_monitor" ] ; then
						#	wm1="${wm1}%{F${FG}}%{B${BG}}%{U${UL}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						#else
						#	wm2="${wm2}%{F${FG}}%{B${BG}}%{U${UL}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						#fi
						if [ "$monitor_name" == "$first_monitor_name" ] ; then
							wm1="${wm1}%{F${FG}}%{B${BG}}%{U${UL}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						else
							wm2="${wm2}%{F${FG}}%{B${BG}}%{U${UL}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						fi
						
						;;
					[LTG]*)
						# layout, state and flags
						# wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
    if [ $num_mon -gt 1 ]; then
		# same output every monitor
    	#printf "%s\n" "%{Sf}%{l}${wm}%{c}${vpn}%{r}${volume} ${mem} ${data} ${hora} %{Sl}%{l}${wm}%{c}${vpn}%{r}${volume} ${mem} ${data} ${hora}"
		# diffents output per monitor (only own workspaces)
    	printf "%s\n" "%{Sf}%{l}${wm1}%{c}%{r}${music} ${vpn} ${volume} ${mem} ${data} ${hora} %{Sl}%{l}${wm2}%{c}%{r}${music} ${vpn} ${volume} ${mem} ${data} ${hora}"
    else
    	printf "%s\n" "%{l}${wm}%{c}${hora}%{r}${mem} ${data}"
    fi
done
