#!/bin/bash

COLOR=$(xrdb -query | grep  color10  | awk '{print $2}')
COLOR_BG=$(xrdb -query | grep background | awk '{print $2}')
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR -sf $COLOR_BG -nf $COLOR"
DMENU="dmenu -i -l 15 -p Choose $COLOR_OPTIONS"
MUSIC_DIR="$HOME/Música"

cd "$MUSIC_DIR"
target=$(ls */ -d | $DMENU) 
#echo "$target"
if [[ "$target" != "" ]]; then
killall cmus 
st -f Inconsolata-11 -c floatterm -g 75x13 -e cmus & disown
#urxvtc -name floatterm -title floatterm -e cmus & disown
sleep 1
cmus-remote --clear -l &
sleep 1
cmus-remote -l "$target" &
sleep 1
cmus-remote --play &
fi

