#!/bin/sh

COLOR=$( $HOME/bin/getcolor  color12 )
COLOR_BG=$( $HOME/bin/getcolor bg )
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR -sf $COLOR_BG -nf $COLOR"
DMENU="dmenu -i -l 15 -p Choose $COLOR_OPTIONS"
CHESS_RESOURCES_DIR="$HOME/altres/chess/_BOOKS_REPOSITORY"

cd "$CHESS_RESOURCES_DIR"
target=$(ls -R -p | grep -v / | $DMENU) 
#echo "$target"
ruta=$(find $PWD -type f -name "*$target*")
echo "$ruta"
[ ! -f "$ruta" ] && exit 0
case $ruta in
	*pdf|*PDF|*djvu) zathura "$ruta" ;;
	*pgn) st -e nvim "$ruta" ;;
	*) herbe "no pdf/no pgn : impossible to load" ;;
esac
