#!/bin/bash

GREEN=$($HOME/bin/getcolor green)
COLOR_BG=$($HOME/bin/getcolor bg)
COLOR_OPTIONS="-nb $COLOR_BG -sb $GREEN -sf $COLOR_BG -nf $GREEN"
DMENU="dmenu -i -l 7 -c -bw 2 -p Connect: $COLOR_OPTIONS"

cd $HOME/.putty/sessions

target=$( ls | grep -v Default | $DMENU ) 
echo "$target"


if [[ "$target" != "Default%20Settings" && "$target" != "" ]]; then
putty -load "$target"
fi

