#!/bin/bash

COLOR=$( $HOME/bin/getcolor color10 )
COLOR_BG=$( $HOME/bin/getcolor bg )
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR -sf $COLOR_BG -nf $COLOR"
DMENU="dmenu -i -l 15 -p Choose $COLOR_OPTIONS"
MUSIC_DIR="$HOME/Música"

cd "$MUSIC_DIR"
target=$(ls */ -d | $DMENU) 
#echo "$target"
if [[ "$target" != "" ]]; then
killall cmus 
# st -f Inconsolata-11 -c floatterm -n stmusic -g 75x15 -e cmus & disown
urxvtc -name stmusic -title floatterm -geometry 78x15 -e cmus & disown
sleep 1
cmus-remote --clear -l &
sleep 1
cmus-remote -l "$target" &
sleep 1
cmus-remote --play &
fi

