#!/bin/sh

PATH_VMs=/opt/qemuVMs
PATH_ISOs=~/altres/ISO
COLOR=$( $HOME/bin/getcolor  color4 )
COLOR_BG=$( $HOME/bin/getcolor bg )
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR -sf $COLOR_BG -nf $COLOR"

msg1="Choose your VM:  "
msg2="Choose the name of the new VM:  "
msg3="Choose an ISO to boot into:  "

# ----------------------------------------------------------------
# ---- CHOOSE WICH VM WE WANNA START (OR CREATE A NEW ONE) -------
# ----------------------------------------------------------------
opcions="NEW VM\\ntest ISO\\n$(ls $PATH_VMs)"
selection=$( printf "$opcions" | dmenu -i  -p "$msg1" $COLOR_OPTIONS)

[ "$selection" = "" ] && exit 0
if [ "$selection" = "NEW VM" ]; then
	echo "we selected NEW VM"
elif [ "$selection" = "test ISO" ]; then
	echo "we wanna test a new ISO"
else
	echo "~/bin/vm.sh -n $selection -p $PATH_VMs &"
	~/bin/vm.sh -n $selection -p $PATH_VMs &
	exit 0
fi


# ----------------------------------------------------------------
# ------- CHOOSE A NAME FOR THE NEW VM ---------------------------
# ----------------------------------------------------------------
if [ "$selection" != "test ISO" ]; then
	vmName=$( printf "" | dmenu -i  -p "$msg2" $COLOR_OPTIONS)

	[ "$vmName" = "" ] && exit 0
	if [ -d "$PATH_VMs/$vmName" ]; then
		herbe "VM name already exists"
		exit 0
	fi
fi

# ----------------------------------------------------------------
# ------ CHOOSE AN ISO TO BOOT THE NEW VM WITH -------------------
# ----------------------------------------------------------------
opcions="$(ls $PATH_ISOs | grep iso)"
vmISO=$( printf "$opcions" | dmenu -i -l 15 -p "$msg3" $COLOR_OPTIONS)

[ "$vmISO" = "" ] && exit 0
if [ ! -f "$PATH_ISOs/$vmISO" ]; then
	herbe "Select a valid ISO"
	exit 0
fi

if [ "$selection" = "test ISO" ]; then
	~/bin/vm.sh -n zztest -d $PATH_ISOs/$vmISO -p $PATH_VMs  &
else
	echo "~/bin/vm.sh -n $vmName -d $PATH_ISOs/$vmISO -p $PATH_VMs &"
	~/bin/vm.sh -n $vmName -d $PATH_ISOs/$vmISO -p $PATH_VMs  &
fi

exit 0
