#! /bin/sh

# dmenu script to open certain scripts or config files
# The files to choose from are hardcoded in the script.

CONSOLE=st
EDITOR=nvim

TEMP_DIR=/tmp/myconfigs
TEMP_FILE="$TEMP_DIR/myconfigs"
[ ! -d "$TEMP_DIR" ] && mkdir -p $TEMP_DIR 

COLOR=$($HOME/bin/getcolor brightyellow )
COLOR_BG=$($HOME/bin/getcolor bg)
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR  -sf $COLOR_BG -nf $COLOR"
DMENU="dmenu -i -l 8 -c -bw 2  -p Choose: $COLOR_OPTIONS"

if [ ! -f "$TEMP_FILE" ]; then
	echo "/opt/sdr/config/sdr.properties" > $TEMP_FILE
	echo "/opt/sdr/sdr_respostes_basiques_suport.txt" >> $TEMP_FILE
	echo "$HOME/.config/sxhkd/sxhkdrc" >> $TEMP_FILE
	echo "/opt/sdr/working.txt" >> $TEMP_FILE
	echo "$HOME/bin/dmenu/master" >> $TEMP_FILE
	echo "$HOME/bin/dmenu/openConfig" >> $TEMP_FILE
	echo "$HOME/.config/nvim/init.vim" >> $TEMP_FILE
    echo "$HOME/.vim/plugged/lightline.vim/autoload/lightline/colorscheme/xavi2.vim" >> $TEMP_FILE
    echo "/opt/git_projects/qmk_firmware/keyboards/crkbd/keymaps/xavi/keymap.c" >> $TEMP_FILE
fi

chosen=$( cat $TEMP_FILE | awk -F'/' '{print $NF}' | $DMENU )
[ -z $chosen ] && exit 0
file2open=$( cat $TEMP_FILE | grep $chosen )
[ ! -f $file2open ] && exit 0

#bspc node -d 6 && nvim $chosen
$CONSOLE -e $EDITOR $file2open

