#!/bin/sh

COLOR_RED="$(~/bin/getcolor 'brightred')"
COLOR_BG="$(~/bin/getcolor 'bg')"
COLOR_OPTIONS="-nb $COLOR_BG -sb $COLOR_RED -sf $COLOR_BG -nf $COLOR_RED"
DMENU="dmenu -c -i -l 8 -bw 4 -fn UbuntuMono:13 $COLOR_OPTIONS"

doStuff() {
    case "$1" in
        lock)
            ~/bin/lock
            #slock
            ;;
        logout)
            window_manager=$( xprop -id $(xprop -root _NET_SUPPORTING_WM_CHECK | cut -d\# -f2) | grep WM_NAME | awk '{print $3}' | tr -d '"' )
            if [ "$window_manager" = "i3" ]
            then
                i3-msg exit
            elif [ "" !=  "$(pidof bspwm)" ]
            then
                bspc quit
            elif [ "" !=  "$(pidof dwm)" ]
            then
                dwmc quit
            fi
            ;;
        suspend)
            sudo pm-suspend | i3lock
            ;;
        hibernate)
            lock && systemctl hibernate
            ;;
        reboot)
            systemctl reboot
            ;;
        shutdown)
            systemctl poweroff
            ;;
        *)
            echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
            exit 2
    esac
}

opcions="LOCK\\n-\\n-\\nLOGOUT\\nREBOOT\\nSHUTDOWN"
selection=$( printf "$opcions" | $DMENU )

case "$selection" in
    LOCK)
        doStuff lock
        ;;
    LOGOUT)
        doStuff logout
        ;;
    REBOOT)
        doStuff reboot
        ;;
    SHUTDOWN)
        doStuff shutdown
        ;;
esac

exit 0
