#! /bin/bash
#
# A dmenu ivoox podcasts audio player 
#    https://mytuner-radio.com/podcast/siglo-21-radio-3-281404669
#    https://mytuner-radio.com/podcast/a-altas-horas1-a-altas-horas-1436728725
#    https://mytuner-radio.com/podcast/turbo-3-radio-3-730325989
#
# 25/01/2021 - xavi 
#
# echo "seek -20" > /tmp/mpv.fifo
# echo "seek 20" > /tmp/mpv.fifo
# echo "stop" > /tmp/mpv.fifo
# echo '{"command": ["cycle", "pause"]}' > /tmp/mpv.fifo
#

#
#  https://www.rtve.es/play/audios/turbo-3/
#  curl https://www.rtve.es/play/audios/turbo-3/ | grep data-idasset
#  6698188 
#  https://api.rtve.es/api/audios/6699095.json
#  curl https://www.rtve.es/play/audios/turbo-3/ | grep "programTitle"   [tots menys el primer!!!!]
#  https://www.rtve.es/play/audios/turbo-3/crudo-pimento-kiko-veneno-abraxas-broken-bells-11-10-22/6711693/
#    (aquí tenim tot: nom + id + data)
#

FOLDER_TEMP=/tmp/musicpodcasts
FOLDER_MUSIC=~/Música/ivoox
TEMP_MP3_FILE_NAME="podcast_tmp.mp3"

getURL() {
	case "$1" in
        "Siglo 21")
            URL="https://www.rtve.es/play/audios/turbo-3/"
            NAME=siglo21
            ;;
        "Atmosfera")
            URL="https://www.rtve.es/play/audios/atmosfera/"
            NAME=atmosfera
            ;;
        "Turbo 3")
            URL="https://www.rtve.es/play/audios/turbo-3/"
            #URL="https://mytuner-radio.com/podcast/turbo-3-radio-3-730325989"
            NAME=turbo3
            ;;
        "A altas horas")
            URL="https://mytuner-radio.com/podcast/a-altas-horas1-a-altas-horas-1436728725"
            NAME=aaltashoras
            ;;
        *)
            exit 2
    esac
}

playWithMpv() {
    pkill mpv
    mpv --no-audio-display "$FOLDER_MUSIC"/"$1" &
    sleep 1s
    mpvc -V 75 # volume to 60%
}

openMediaFile() {
    #st -n stmusic -g 85x13 -f UbuntuMonoNerdFont-12 -e cmus & disown
	urxvtc -name stmusic -geometry 80x15 -title floatterm -e cmus & disown
	#xterm -name stmusic -geometry 80x15 -title floatterm -e cmus & disown
	sleep 1
	cmus-remote --clear -l &
	sleep 1
	cmus-remote -l "$1" &
	sleep 0.5
	cmus-remote --play &
}

downloadMediaFile() {
	mp3url="$1"
	dest_mp3_file="$2"
	if [ "$dest_mp3_file" = "" ]; then 
		curl -L -o "/tmp/$TEMP_MP3_FILE_NAME" "$mp3url" 
		mv "/tmp/$TEMP_MP3_FILE_NAME" "$FOLDER_MUSIC"
	else
		# not downloading directly to final folder because curl doesn't like long filenames
        if [ ! -f "$FOLDER_MUSIC/$dest_mp3_file" ]; then
		    curl -o "$FOLDER_TEMP/$TEMP_MP3_FILE_NAME" "$mp3url" 
		    mv "$FOLDER_TEMP/$TEMP_MP3_FILE_NAME" "$FOLDER_MUSIC/$dest_mp3_file"
        fi
	fi
}




# first we select which program we wanna download podcasts from
#
pogrames_disponibles="Siglo 21\\nTurbo 3\\nAtmosfera\\nA altas horas"
selection=$( printf "$pogrames_disponibles" | dmenu -i  -p "Chose program" )
[ "$selection" = "" ] && exit 0
PROGRAM=$selection

getURL "$selection"

#NAME=turbo3
[ ! -d "$FOLDER_TEMP" ] && mkdir -p $FOLDER_TEMP
TMP_HTML="$FOLDER_TEMP/""$NAME""_$(date  +'%Y-%m-%d')"
DATA_NAMES="$TMP_HTML""names"
DATA_IDS="$TMP_HTML""ids"
DATA_mp3="$TMP_HTML""mp3"
DATA_DAYS="$TMP_HTML""days"
FULL_DATA="$TMP_HTML""dmenu"
TMP_DATA="$TMP_HTML""tmp_d1.json"
TMP_JSON="$TMP_HTML""tmp_d2.json"



if [ ! -f $TMP_HTML ]; then
    curl $URL > $TMP_HTML
    
    cat $TMP_HTML | grep datemi | awk -F'>' '{print $2}' | awk -F '<' '{print $1}' > $DATA_DAYS
    cat $TMP_HTML | grep 'Escuchar emis' | awk -F'Escuchar emisión ' '{print $2}' | awk -F'"--' '{print $1}' | sed "s|'||g" > $DATA_NAMES
    cat $TMP_HTML | grep data-idasset | awk -F'data-idasset="' '{print $2}' | sed 's/\"//g' > $DATA_IDS
    
    readarray -t arrayD < $DATA_DAYS
    readarray -t arrayN < $DATA_NAMES
    readarray -t arrayM < $DATA_IDS
     
    [ -f $FULL_DATA ] && rm $FULL_DATA
    
    for index in "${!arrayD[@]}"; do
        echo "${arrayD[$index]} >> ${arrayN[$index]} >> ${arrayM[$index]}" >> $FULL_DATA
    done
fi


selection=$( cat $FULL_DATA | awk -F ' >> ' '{print $1 " -- " $2}' | dmenu -p "choose episode: " -l 20 )
[ -z "$selection" ] && exit 0
data=$( echo $selection | awk -F' -- ' '{print $1}' )
name=$( echo $selection | awk -F' -- ' '{print $2}' )
mp3file="$(echo "$data-$name".mp3)"
mp3file="$(echo "$NAME""_""$mp3file" | sed "s| |_|g" | sed "s|\/|-|g"  )"

selected=$( cat $FULL_DATA | grep "$data" )
[ -z "$selected" ] && exit 0
#echo "selected :::: $selected"
#echo "mp3file :::: $mp3file"

id=$( echo $selected | awk -F' >> ' '{print $3}' )
url="https://api.rtve.es/api/audios/$id.json"
#echo $url
curl -o $TMP_DATA $url
jq '.' $TMP_DATA > $TMP_JSON

cat $TMP_JSON | grep mp3 > $TMP_DATA
cat $TMP_DATA | awk -F'": "' '{print $2}' | awk -F'"' '{print $1}' > $TMP_JSON

downloadMediaFile "$(cat $TMP_JSON)" "$mp3file" 
playWithMpv "$mp3file"

