#!/bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1 &
wmname LG3D &
#dunst &

if type xcompmgr > /dev/null; then
    xcompmgr &
fi
if type picom > /dev/null; then
    picom &
fi
if type compton > /dev/null; then
    compton &
fi
if type urxvtd > /dev/null; then
    urxvtd -q -o -f &
fi

#manage-monitors &
#xautolock -time 20 -locker "$HOME/bin/i3/lock" &

wallpaper-loop &
xrdb ~/.Xresources &

#dwmblocks &
#sxhkd -c ~/.config/sxhkd/sxhkdrc.dwm &
$HOME/bin/dwm/sbar &

exec dwm
